import type { AnyPgColumn } from "drizzle-orm/pg-core";
import { pgSchema, boolean, date, integer, jsonb, text, timestamp, uuid, primaryKey } from "drizzle-orm/pg-core";

/**
 * The application's own schema, as Drizzle sees it.
 *
 * GENERATED by scripts/gen-app-schema.mjs from the live `app` schema -- do not
 * edit by hand, re-run it. 45 tables of column names is exactly the kind of
 * transcription that fails silently: a mistyped SQL name is a column the app
 * writes to and never reads back, with no error anywhere.
 *
 * `lib/db/schema.ts` beside this file is the `public` schema Django built. It
 * stays until the deploy, and nothing new should be written against it.
 */
export const app = pgSchema("app");

export const account = app.table("account", {
  id: uuid().primaryKey().defaultRandom(),
  username: text().notNull(),
  email: text().notNull().default(''),
  firstName: text("first_name").notNull().default(''),
  lastName: text("last_name").notNull().default(''),
  isStaff: boolean("is_staff").notNull().default(false),
  isActive: boolean("is_active").notNull().default(true),
  joinedAt: timestamp("joined_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  lastSeenAt: timestamp("last_seen_at", { withTimezone: true, mode: "string" }),
});

export const accountIdentity = app.table("account_identity", {
  id: uuid().primaryKey().defaultRandom(),
  accountId: uuid("account_id").references((): AnyPgColumn => account.id).notNull(),
  provider: text().notNull(),
  providerUid: text("provider_uid").notNull(),
  extra: jsonb().notNull().default({}),
  connectedAt: timestamp("connected_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
});

export const application = app.table("application", {
  id: uuid().primaryKey().defaultRandom(),
  organizationId: uuid("organization_id").references((): AnyPgColumn => organization.id).notNull(),
  title: text().notNull(),
  statusId: uuid("status_id").references((): AnyPgColumn => applicationStatus.id),
  employmentTypeId: uuid("employment_type_id").references((): AnyPgColumn => employmentType.id),
  workModeId: uuid("work_mode_id").references((): AnyPgColumn => workMode.id),
  locationId: uuid("location_id").references((): AnyPgColumn => location.id),
  sourceId: uuid("source_id").references((): AnyPgColumn => applicationSource.id),
  salaryRange: text("salary_range").notNull().default(''),
  lessonsLearned: text("lessons_learned").notNull().default(''),
});

export const applicationSource = app.table("application_source", {
  id: uuid().primaryKey().defaultRandom(),
  slug: text().notNull(),
  label: text().notNull(),
});

export const applicationStatus = app.table("application_status", {
  id: uuid().primaryKey().defaultRandom(),
  slug: text().notNull(),
  label: text().notNull(),
  position: integer().notNull().default(0),
});

export const applicationStep = app.table("application_step", {
  id: uuid().primaryKey().defaultRandom(),
  applicationId: uuid("application_id").references((): AnyPgColumn => application.id).notNull(),
  occurredAt: timestamp("occurred_at", { withTimezone: true, mode: "string" }),
  title: text().notNull(),
  details: text().notNull().default(''),
  notes: text().notNull().default(''),
  position: integer().notNull().default(0),
});

export const award = app.table("award", {
  id: uuid().primaryKey().defaultRandom(),
  organizationId: uuid("organization_id").references((): AnyPgColumn => organization.id).notNull(),
  title: text().notNull(),
  credentialUrl: text("credential_url").notNull().default(''),
  description: text().notNull().default(''),
  issued: date().notNull(),
});

export const blogImage = app.table("blog_image", {
  id: uuid().primaryKey().defaultRandom(),
  postId: uuid("post_id").references((): AnyPgColumn => blogPost.id).notNull(),
  mediaId: uuid("media_id").references((): AnyPgColumn => mediaAsset.id).notNull(),
  position: integer().notNull().default(0),
});

export const blogPost = app.table("blog_post", {
  id: uuid().primaryKey().defaultRandom(),
  slug: text().notNull(),
  title: text().notNull(),
  description: text().notNull().default(''),
  contentHtml: text("content_html").notNull().default(''),
  categoryId: uuid("category_id").references((): AnyPgColumn => category.id),
  authorName: text("author_name").notNull().default(''),
  authorUsername: text("author_username").notNull().default(''),
  authorImageId: uuid("author_image_id").references((): AnyPgColumn => mediaAsset.id),
  isFeatured: boolean("is_featured").notNull().default(false),
  readTime: integer("read_time"),
  views: integer().notNull().default(0),
  publishedAt: timestamp("published_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
});

export const blogTag = app.table("blog_tag", {
  postId: uuid("post_id").references((): AnyPgColumn => blogPost.id).notNull(),
  tagId: uuid("tag_id").references((): AnyPgColumn => tag.id).notNull(),
  position: integer().notNull().default(0),
}, (t) => [primaryKey({ columns: [t.postId, t.tagId] })]);

export const category = app.table("category", {
  id: uuid().primaryKey().defaultRandom(),
  kind: text().notNull(),
  slug: text().notNull(),
  label: text().notNull(),
  position: integer().notNull().default(0),
});

export const certification = app.table("certification", {
  id: uuid().primaryKey().defaultRandom(),
  organizationId: uuid("organization_id").references((): AnyPgColumn => organization.id).notNull(),
  title: text().notNull(),
  credentialUrl: text("credential_url").notNull().default(''),
  isFeatured: boolean("is_featured").notNull().default(false),
  issued: date().notNull(),
});

export const certificationAchievement = app.table("certification_achievement", {
  id: uuid().primaryKey().defaultRandom(),
  certificationId: uuid("certification_id").references((): AnyPgColumn => certification.id).notNull(),
  body: text().notNull(),
  position: integer().notNull().default(0),
});

export const comment = app.table("comment", {
  id: uuid().primaryKey().defaultRandom(),
  accountId: uuid("account_id").references((): AnyPgColumn => account.id).notNull(),
  targetKind: text("target_kind").notNull(),
  targetId: uuid("target_id").notNull(),
  body: text().notNull(),
  isDeleted: boolean("is_deleted").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  replyToId: uuid("reply_to_id").references((): AnyPgColumn => comment.id),
});

export const education = app.table("education", {
  id: uuid().primaryKey().defaultRandom(),
  organizationId: uuid("organization_id").references((): AnyPgColumn => organization.id).notNull(),
  degree: text().notNull(),
  alias: text().notNull().default(''),
  isLast: boolean("is_last").notNull().default(false),
  locationId: uuid("location_id").references((): AnyPgColumn => location.id),
  years: text().notNull().default(''),
  dateStart: date("date_start"),
  dateEnd: date("date_end"),
});

export const educationAchievement = app.table("education_achievement", {
  id: uuid().primaryKey().defaultRandom(),
  educationId: uuid("education_id").references((): AnyPgColumn => education.id).notNull(),
  body: text().notNull(),
  position: integer().notNull().default(0),
});

export const employmentType = app.table("employment_type", {
  id: uuid().primaryKey().defaultRandom(),
  slug: text().notNull(),
  label: text().notNull(),
  position: integer().notNull().default(0),
});

export const experience = app.table("experience", {
  id: uuid().primaryKey().defaultRandom(),
  organizationId: uuid("organization_id").references((): AnyPgColumn => organization.id).notNull(),
  title: text().notNull(),
  employmentTypeId: uuid("employment_type_id").references((): AnyPgColumn => employmentType.id),
  workModeId: uuid("work_mode_id").references((): AnyPgColumn => workMode.id),
  locationId: uuid("location_id").references((): AnyPgColumn => location.id),
  isCurrent: boolean("is_current").notNull().default(false),
  periodStart: date("period_start").notNull(),
  periodEnd: date("period_end"),
  position: integer().notNull().default(0),
});

export const experienceTask = app.table("experience_task", {
  id: uuid().primaryKey().defaultRandom(),
  experienceId: uuid("experience_id").references((): AnyPgColumn => experience.id).notNull(),
  body: text().notNull(),
  position: integer().notNull().default(0),
});

export const guestMessage = app.table("guest_message", {
  id: uuid().primaryKey().defaultRandom(),
  accountId: uuid("account_id").references((): AnyPgColumn => account.id).notNull(),
  body: text().notNull(),
  postedAt: timestamp("posted_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  replyToId: uuid("reply_to_id").references((): AnyPgColumn => guestMessage.id),
  isPinned: boolean("is_pinned").notNull().default(false),
  pinnedAt: timestamp("pinned_at", { withTimezone: true, mode: "string" }),
});

export const guestProfile = app.table("guest_profile", {
  id: uuid().primaryKey().defaultRandom(),
  accountId: uuid("account_id").references((): AnyPgColumn => account.id).notNull(),
  isAuthor: boolean("is_author").notNull().default(false),
  isCoAuthor: boolean("is_co_author").notNull().default(false),
  coAuthorOrder: integer("co_author_order").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
});

export const hiringListItem = app.table("hiring_list_item", {
  id: uuid().primaryKey().defaultRandom(),
  hiringProfileId: uuid("hiring_profile_id").references((): AnyPgColumn => hiringProfile.id).notNull(),
  kind: text().notNull(),
  body: text().notNull(),
  position: integer().notNull().default(0),
});

export const hiringProfile = app.table("hiring_profile", {
  id: uuid().primaryKey().defaultRandom(),
  companyName: text("company_name").notNull(),
  companyDescription: text("company_description").notNull().default(''),
  website: text().notNull().default(''),
  hiringStatus: text("hiring_status").notNull().default(''),
  contactEmail: text("contact_email").notNull().default(''),
  contactApplicationEmail: text("contact_application_email").notNull().default(''),
  contactResponseTime: text("contact_response_time").notNull().default(''),
  contactInterviewProcess: text("contact_interview_process").notNull().default(''),
  additionalNotes: text("additional_notes").notNull().default(''),
});

export const jobOpening = app.table("job_opening", {
  id: uuid().primaryKey().defaultRandom(),
  hiringProfileId: uuid("hiring_profile_id").references((): AnyPgColumn => hiringProfile.id).notNull(),
  title: text().notNull(),
  employmentTypeId: uuid("employment_type_id").references((): AnyPgColumn => employmentType.id),
  locationId: uuid("location_id").references((): AnyPgColumn => location.id),
  salaryRange: text("salary_range").notNull().default(''),
  experienceRequired: text("experience_required").notNull().default(''),
  position: integer().notNull().default(0),
});

export const jobOpeningListItem = app.table("job_opening_list_item", {
  id: uuid().primaryKey().defaultRandom(),
  jobOpeningId: uuid("job_opening_id").references((): AnyPgColumn => jobOpening.id).notNull(),
  kind: text().notNull(),
  body: text().notNull(),
  position: integer().notNull().default(0),
});

export const legalDocument = app.table("legal_document", {
  id: uuid().primaryKey().defaultRandom(),
  slug: text().notNull(),
  title: text().notNull(),
  documentType: text("document_type").notNull(),
  summary: text().notNull().default(''),
  isPublished: boolean("is_published").notNull().default(true),
  lastUpdated: timestamp("last_updated", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  position: integer().notNull().default(0),
});

export const legalSection = app.table("legal_section", {
  id: uuid().primaryKey().defaultRandom(),
  documentId: uuid("document_id").references((): AnyPgColumn => legalDocument.id).notNull(),
  parentId: uuid("parent_id").references((): AnyPgColumn => legalSection.id),
  heading: text().notNull(),
  body: text().notNull().default(''),
  items: jsonb().notNull().default([]),
  position: integer().notNull().default(0),
});

export const location = app.table("location", {
  id: uuid().primaryKey().defaultRandom(),
  city: text().notNull().default(''),
  region: text().notNull().default(''),
  country: text().notNull().default(''),
  flag: text().notNull().default(''),
  mapUrl: text("map_url").notNull().default(''),
});

export const mediaAsset = app.table("media_asset", {
  id: uuid().primaryKey().defaultRandom(),
  storageKey: text("storage_key").notNull(),
  originalFilename: text("original_filename").notNull().default(''),
  alt: text().notNull().default(''),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  source: text().notNull().default('storage'),
});

export const openToWorkListItem = app.table("open_to_work_list_item", {
  id: uuid().primaryKey().defaultRandom(),
  openToWorkProfileId: uuid("open_to_work_profile_id").references((): AnyPgColumn => openToWorkProfile.id).notNull(),
  kind: text().notNull(),
  body: text().notNull(),
  locationId: uuid("location_id").references((): AnyPgColumn => location.id),
  position: integer().notNull().default(0),
});

export const openToWorkProfile = app.table("open_to_work_profile", {
  id: uuid().primaryKey().defaultRandom(),
  status: text().notNull().default(''),
  availability: text().notNull().default(''),
  remote: boolean().notNull().default(false),
  relocation: boolean().notNull().default(false),
  showAllToolsSkills: boolean("show_all_tools_skills").notNull().default(false),
  experienceLevel: text("experience_level").notNull().default(''),
  salaryExpectation: text("salary_expectation").notNull().default(''),
  noticePeriod: text("notice_period").notNull().default(''),
  workAuthorization: text("work_authorization").notNull().default(''),
  contactPreference: text("contact_preference").notNull().default(''),
  interviewAvailability: text("interview_availability").notNull().default(''),
  additionalNotes: text("additional_notes").notNull().default(''),
});

export const organization = app.table("organization", {
  id: uuid().primaryKey().defaultRandom(),
  slug: text().notNull(),
  name: text().notNull(),
  website: text().notNull().default(''),
  logoId: uuid("logo_id").references((): AnyPgColumn => mediaAsset.id),
});

export const portfolioHighlight = app.table("portfolio_highlight", {
  id: uuid().primaryKey().defaultRandom(),
  openToWorkProfileId: uuid("open_to_work_profile_id").references((): AnyPgColumn => openToWorkProfile.id).notNull(),
  title: text().notNull(),
  description: text().notNull().default(''),
  position: integer().notNull().default(0),
});

export const profile = app.table("profile", {
  id: uuid().primaryKey().defaultRandom(),
  name: text().notNull(),
  firstName: text("first_name").notNull().default(''),
  lastName: text("last_name").notNull().default(''),
  username: text().notNull(),
  aka: text().notNull().default(''),
  role: text().notNull().default(''),
  imageId: uuid("image_id").references((): AnyPgColumn => mediaAsset.id),
  locationId: uuid("location_id").references((): AnyPgColumn => location.id),
  residency: text().notNull().default(''),
  isOpenToWork: boolean("is_open_to_work").notNull().default(false),
  isHiring: boolean("is_hiring").notNull().default(false),
  isSick: boolean("is_sick").notNull().default(false),
  shortDescription: text("short_description").notNull().default(''),
  shortBio: text("short_bio").notNull().default(''),
  shortCta: text("short_cta").notNull().default(''),
  longDescription: text("long_description").notNull().default(''),
  storiesHtml: text("stories_html").notNull().default(''),
  personalWebsite: text("personal_website").notNull().default(''),
});

export const profileLink = app.table("profile_link", {
  id: uuid().primaryKey().defaultRandom(),
  profileId: uuid("profile_id").references((): AnyPgColumn => profile.id).notNull(),
  kind: text().notNull(),
  platform: text().notNull(),
  url: text().notNull(),
  position: integer().notNull().default(0),
});

export const profileSkillHighlight = app.table("profile_skill_highlight", {
  id: uuid().primaryKey().defaultRandom(),
  profileId: uuid("profile_id").references((): AnyPgColumn => profile.id).notNull(),
  skillId: uuid("skill_id").references((): AnyPgColumn => skill.id).notNull(),
  position: integer().notNull().default(0),
});

export const project = app.table("project", {
  id: uuid().primaryKey().defaultRandom(),
  slug: text().notNull(),
  title: text().notNull(),
  headline: text().notNull().default(''),
  descriptionHtml: text("description_html").notNull().default(''),
  githubUrl: text("github_url"),
  demoUrl: text("demo_url"),
  categoryId: uuid("category_id").references((): AnyPgColumn => category.id),
  statusId: uuid("status_id").references((): AnyPgColumn => projectStatus.id),
  isFeatured: boolean("is_featured").notNull().default(false),
  featuredPriority: integer("featured_priority"),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
});

export const projectFeature = app.table("project_feature", {
  id: uuid().primaryKey().defaultRandom(),
  projectId: uuid("project_id").references((): AnyPgColumn => project.id).notNull(),
  title: text().notNull(),
  description: text().notNull().default(''),
  position: integer().notNull().default(0),
});

export const projectImage = app.table("project_image", {
  id: uuid().primaryKey().defaultRandom(),
  projectId: uuid("project_id").references((): AnyPgColumn => project.id).notNull(),
  mediaId: uuid("media_id").references((): AnyPgColumn => mediaAsset.id).notNull(),
  position: integer().notNull().default(0),
});

export const projectSkill = app.table("project_skill", {
  projectId: uuid("project_id").references((): AnyPgColumn => project.id).notNull(),
  skillId: uuid("skill_id").references((): AnyPgColumn => skill.id).notNull(),
  position: integer().notNull().default(0),
}, (t) => [primaryKey({ columns: [t.projectId, t.skillId] })]);

export const projectStatus = app.table("project_status", {
  id: uuid().primaryKey().defaultRandom(),
  slug: text().notNull(),
  label: text().notNull(),
  position: integer().notNull().default(0),
});

export const projectTag = app.table("project_tag", {
  projectId: uuid("project_id").references((): AnyPgColumn => project.id).notNull(),
  tagId: uuid("tag_id").references((): AnyPgColumn => tag.id).notNull(),
  position: integer().notNull().default(0),
}, (t) => [primaryKey({ columns: [t.projectId, t.tagId] })]);

export const skill = app.table("skill", {
  id: uuid().primaryKey().defaultRandom(),
  slug: text().notNull(),
  name: text().notNull(),
  description: text().notNull().default(''),
  categoryId: uuid("category_id").references((): AnyPgColumn => category.id),
  iconId: uuid("icon_id").references((): AnyPgColumn => mediaAsset.id),
});

export const tag = app.table("tag", {
  id: uuid().primaryKey().defaultRandom(),
  slug: text().notNull(),
  label: text().notNull(),
});

export const workMode = app.table("work_mode", {
  id: uuid().primaryKey().defaultRandom(),
  slug: text().notNull(),
  label: text().notNull(),
  position: integer().notNull().default(0),
});
