# Generated by Django 6.0.6 on 2026-08-09 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HiringProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('hiring_status', models.CharField(blank=True, max_length=100)),
                ('application_process', models.JSONField(blank=True, default=list)),
                ('company_culture', models.JSONField(blank=True, default=list)),
                ('requirements_general', models.JSONField(blank=True, default=list)),
                ('requirements_technical', models.JSONField(blank=True, default=list)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_application_email', models.EmailField(blank=True, max_length=254)),
                ('contact_response_time', models.CharField(blank=True, max_length=255)),
                ('contact_interview_process', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Hiring Profile',
                'verbose_name_plural': 'Hiring Profile',
            },
        ),
        migrations.CreateModel(
            name='OpenToWorkProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=100)),
                ('availability', models.CharField(blank=True, max_length=100)),
                ('remote', models.BooleanField(default=False)),
                ('relocation', models.BooleanField(default=False)),
                ('show_all_tools_skills', models.BooleanField(default=False)),
                ('type', models.JSONField(blank=True, default=list)),
                ('preferred_roles', models.JSONField(blank=True, default=list)),
                ('skills_highlight', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('preferred_locations', models.JSONField(blank=True, default=list)),
                ('location_types', models.JSONField(blank=True, default=list)),
                ('remote_locations', models.JSONField(blank=True, default=list)),
                ('experience_level', models.CharField(blank=True, max_length=100)),
                ('salary_expectation', models.CharField(blank=True, max_length=100)),
                ('notice_period', models.CharField(blank=True, max_length=100)),
                ('work_authorization', models.CharField(blank=True, max_length=100)),
                ('contact_preference', models.CharField(blank=True, max_length=100)),
                ('interview_availability', models.CharField(blank=True, max_length=255)),
                ('additional_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Open To Work Profile',
                'verbose_name_plural': 'Open To Work Profile',
            },
        ),
        migrations.CreateModel(
            name='PortfolioHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('open_to_work_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_highlights', to='openhire.opentoworkprofile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('experience_required', models.CharField(blank=True, max_length=255)),
                ('skills_required', models.JSONField(blank=True, default=list)),
                ('responsibilities', models.JSONField(blank=True, default=list)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('hiring_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='openhire.hiringprofile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
