# Generated by Django 6.0.7 on 2026-08-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openhire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='type',
            field=models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Self-employed', 'Self-employed'), ('Freelance', 'Freelance'), ('Contract', 'Contract'), ('Internship', 'Internship'), ('Apprenticeship', 'Apprenticeship'), ('Seasonal', 'Seasonal'), ('Scholarship', 'Scholarship')], max_length=100),
        ),
    ]
