# Generated by Django 6.0.7 on 2026-08-16 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('document_type', models.CharField(choices=[('privacy', 'Privacy Policy'), ('terms', 'Terms & Conditions'), ('cookies', 'Cookie Policy'), ('other', 'Other')], default='other', max_length=20)),
                ('summary', models.TextField(blank=True, help_text='Short intro shown under the title, and used as the meta description.')),
                ('is_published', models.BooleanField(default=True, help_text='Unpublished documents 404 and stay out of the sitemap.')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
                'indexes': [models.Index(fields=['is_published', 'slug'], name='legal_legal_is_publ_03b95d_idx')],
            },
        ),
        migrations.CreateModel(
            name='LegalSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, help_text='Optional prose shown above the list. Rendered as HTML.')),
                ('items', models.JSONField(blank=True, default=dict, help_text='Definition list: each key is a term, each value its description.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='legal.legaldocument')),
                ('parent', models.ForeignKey(blank=True, help_text='Leave empty for a top-level section. One level of nesting only.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='legal.legalsection')),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['document', 'order'], name='legal_legal_documen_83d36e_idx')],
            },
        ),
    ]
