-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "about_skill" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "about_skill_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"slug" varchar(50) NOT NULL,
	"name" varchar(100) NOT NULL,
	"description" text NOT NULL,
	"icon_svg" varchar(500) NOT NULL,
	"category" varchar(100) NOT NULL,
	CONSTRAINT "about_skill_slug_key" UNIQUE("slug")
);
--> statement-breakpoint
ALTER TABLE "about_skill" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "about_experience" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "about_experience_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"title" varchar(255) NOT NULL,
	"employment_type" varchar(50) NOT NULL,
	"location_type" varchar(50) NOT NULL,
	"location" varchar(255) NOT NULL,
	"is_current" boolean NOT NULL,
	"responsibilities" jsonb NOT NULL,
	"sort_order" integer NOT NULL,
	"period_start" date NOT NULL,
	"period_end" date,
	"organization_id" bigint NOT NULL,
	CONSTRAINT "about_experience_sort_order_check" CHECK (sort_order >= 0)
);
--> statement-breakpoint
ALTER TABLE "about_experience" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "blog_blogimage" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "blog_blogimage_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"image" varchar(100) NOT NULL,
	"original_filename" varchar(255) NOT NULL,
	"order" integer NOT NULL,
	"blog_id" bigint NOT NULL,
	CONSTRAINT "blog_blogimage_order_check" CHECK ("order" >= 0)
);
--> statement-breakpoint
ALTER TABLE "blog_blogimage" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "projects_project" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "projects_project_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"title" varchar(255) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"headline" varchar(500) NOT NULL,
	"description" jsonb NOT NULL,
	"github_url" varchar(200),
	"demo_url" varchar(200),
	"category" varchar(255) NOT NULL,
	"tags" jsonb NOT NULL,
	"is_featured" boolean NOT NULL,
	"featured_priority" integer,
	"status" varchar(32) NOT NULL,
	"created_at" timestamp with time zone,
	"updated_at" timestamp with time zone,
	CONSTRAINT "projects_project_slug_key" UNIQUE("slug")
);
--> statement-breakpoint
ALTER TABLE "projects_project" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "socialaccount_socialapp" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "socialaccount_socialapp_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"provider" varchar(30) NOT NULL,
	"name" varchar(40) NOT NULL,
	"client_id" varchar(191) NOT NULL,
	"secret" varchar(191) NOT NULL,
	"key" varchar(191) NOT NULL,
	"provider_id" varchar(200) NOT NULL,
	"settings" jsonb NOT NULL
);
--> statement-breakpoint
ALTER TABLE "socialaccount_socialapp" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "about_profileskillhighlight" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "about_profileskillhighlight_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"order" integer NOT NULL,
	"profile_id" bigint NOT NULL,
	"skill_id" bigint NOT NULL,
	CONSTRAINT "unique_profile_skill_highlight" UNIQUE("profile_id","skill_id"),
	CONSTRAINT "about_profileskillhighlight_order_check" CHECK ("order" >= 0)
);
--> statement-breakpoint
ALTER TABLE "about_profileskillhighlight" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "about_certification" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "about_certification_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"title" varchar(255) NOT NULL,
	"credential_url" varchar(200) NOT NULL,
	"is_featured" boolean NOT NULL,
	"achievements" jsonb NOT NULL,
	"issued" date NOT NULL,
	"organization_id" bigint NOT NULL
);
--> statement-breakpoint
ALTER TABLE "about_certification" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "projects_project_tech_stack" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "projects_project_tech_stack_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"project_id" bigint NOT NULL,
	"skill_id" bigint NOT NULL,
	CONSTRAINT "projects_project_tech_stack_project_id_skill_id_5501e506_uniq" UNIQUE("project_id","skill_id")
);
--> statement-breakpoint
ALTER TABLE "projects_project_tech_stack" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "django_migrations" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "django_migrations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"app" varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"applied" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "django_migrations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "about_award" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "about_award_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"title" varchar(255) NOT NULL,
	"credential_url" varchar(200) NOT NULL,
	"description" text NOT NULL,
	"issued" date NOT NULL,
	"organization_id" bigint NOT NULL
);
--> statement-breakpoint
ALTER TABLE "about_award" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "about_application" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "about_application_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"status" varchar(20) NOT NULL,
	"company_name" varchar(255) NOT NULL,
	"position" varchar(255) NOT NULL,
	"employment_type" varchar(20) NOT NULL,
	"location_type" varchar(20) NOT NULL,
	"location" varchar(255) NOT NULL,
	"applied_via" varchar(20),
	"salary_range" varchar(100),
	"lessons_learned" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "about_application" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "auth_permission" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auth_permission_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"content_type_id" integer NOT NULL,
	"codename" varchar(100) NOT NULL,
	CONSTRAINT "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE("content_type_id","codename")
);
--> statement-breakpoint
ALTER TABLE "auth_permission" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "projects_projectimage" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "projects_projectimage_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"image" varchar(100) NOT NULL,
	"original_filename" varchar(255) NOT NULL,
	"order" integer NOT NULL,
	"project_id" bigint NOT NULL,
	CONSTRAINT "projects_projectimage_order_check" CHECK ("order" >= 0)
);
--> statement-breakpoint
ALTER TABLE "projects_projectimage" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "about_journeystep" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "about_journeystep_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"timestamp" timestamp with time zone,
	"title" varchar(255) NOT NULL,
	"details" text NOT NULL,
	"notes" text NOT NULL,
	"application_id" bigint NOT NULL
);
--> statement-breakpoint
ALTER TABLE "about_journeystep" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "openhire_position" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "openhire_position_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"title" varchar(255) NOT NULL,
	"type" varchar(100) NOT NULL,
	"location" varchar(255) NOT NULL,
	"salary_range" varchar(100) NOT NULL,
	"experience_required" varchar(255) NOT NULL,
	"skills_required" jsonb NOT NULL,
	"responsibilities" jsonb NOT NULL,
	"benefits" jsonb NOT NULL,
	"order" integer NOT NULL,
	"hiring_profile_id" bigint NOT NULL,
	CONSTRAINT "openhire_position_order_check" CHECK ("order" >= 0)
);
--> statement-breakpoint
ALTER TABLE "openhire_position" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "guestbook_userprofile" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "guestbook_userprofile_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"is_author" boolean NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"user_id" integer NOT NULL,
	"co_author_order" integer NOT NULL,
	"is_co_author" boolean NOT NULL,
	CONSTRAINT "guestbook_userprofile_user_id_key" UNIQUE("user_id"),
	CONSTRAINT "guestbook_userprofile_co_author_order_check" CHECK (co_author_order >= 0)
);
--> statement-breakpoint
ALTER TABLE "guestbook_userprofile" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "auth_group_permissions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auth_group_permissions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"group_id" integer NOT NULL,
	"permission_id" integer NOT NULL,
	CONSTRAINT "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE("group_id","permission_id")
);
--> statement-breakpoint
ALTER TABLE "auth_group_permissions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "projects_feature" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "projects_feature_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"title" varchar(255) NOT NULL,
	"description" text NOT NULL,
	"order" integer NOT NULL,
	"project_id" bigint NOT NULL,
	CONSTRAINT "projects_feature_order_check" CHECK ("order" >= 0)
);
--> statement-breakpoint
ALTER TABLE "projects_feature" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "socialaccount_socialaccount" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "socialaccount_socialaccount_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"provider" varchar(200) NOT NULL,
	"uid" varchar(191) NOT NULL,
	"last_login" timestamp with time zone NOT NULL,
	"date_joined" timestamp with time zone NOT NULL,
	"extra_data" jsonb NOT NULL,
	"user_id" integer NOT NULL,
	CONSTRAINT "socialaccount_socialaccount_provider_uid_fc810c6e_uniq" UNIQUE("provider","uid")
);
--> statement-breakpoint
ALTER TABLE "socialaccount_socialaccount" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "about_profile" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "about_profile_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"first_name" varchar(100) NOT NULL,
	"last_name" varchar(100) NOT NULL,
	"username" varchar(100) NOT NULL,
	"aka" varchar(100) NOT NULL,
	"image" varchar(100),
	"personal_website" varchar(200) NOT NULL,
	"cv_main" varchar(200) NOT NULL,
	"cv_latest" varchar(200) NOT NULL,
	"cv_copy" varchar(200) NOT NULL,
	"role" varchar(255) NOT NULL,
	"is_open_to_work" boolean NOT NULL,
	"is_hiring" boolean NOT NULL,
	"is_sick" boolean NOT NULL,
	"short_description" text NOT NULL,
	"short_bio" text NOT NULL,
	"short_cta" text NOT NULL,
	"long_description" text NOT NULL,
	"stories" jsonb NOT NULL,
	"location_regency" varchar(100) NOT NULL,
	"location_residency" varchar(100) NOT NULL,
	"location_province" varchar(100) NOT NULL,
	"location_prov" varchar(100) NOT NULL,
	"location_country" varchar(100) NOT NULL,
	"location_flag" varchar(16) NOT NULL,
	"social_email" varchar(254) NOT NULL,
	"social_github" varchar(200) NOT NULL,
	"social_linkedin" varchar(200) NOT NULL,
	"social_follow_linkedin" varchar(200) NOT NULL,
	"social_instagram" varchar(200) NOT NULL,
	"social_medium" varchar(200) NOT NULL,
	"social_x" varchar(200) NOT NULL,
	"social_website" varchar(200) NOT NULL
);
--> statement-breakpoint
ALTER TABLE "about_profile" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "comments_comment" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "comments_comment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"object_id" integer NOT NULL,
	"body" text NOT NULL,
	"is_deleted" boolean NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"content_type_id" integer NOT NULL,
	"reply_to_id" bigint,
	"user_id" integer NOT NULL,
	CONSTRAINT "comments_comment_object_id_check" CHECK (object_id >= 0)
);
--> statement-breakpoint
ALTER TABLE "comments_comment" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "openhire_opentoworkprofile" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "openhire_opentoworkprofile_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"status" varchar(100) NOT NULL,
	"availability" varchar(100) NOT NULL,
	"remote" boolean NOT NULL,
	"relocation" boolean NOT NULL,
	"show_all_tools_skills" boolean NOT NULL,
	"type" jsonb NOT NULL,
	"preferred_roles" jsonb NOT NULL,
	"skills_highlight" jsonb NOT NULL,
	"languages" jsonb NOT NULL,
	"preferred_locations" jsonb NOT NULL,
	"location_types" jsonb NOT NULL,
	"remote_locations" jsonb NOT NULL,
	"experience_level" varchar(100) NOT NULL,
	"salary_expectation" varchar(100) NOT NULL,
	"notice_period" varchar(100) NOT NULL,
	"work_authorization" varchar(100) NOT NULL,
	"contact_preference" varchar(100) NOT NULL,
	"interview_availability" varchar(255) NOT NULL,
	"additional_notes" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "openhire_opentoworkprofile" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "django_session" (
	"session_key" varchar(40) PRIMARY KEY NOT NULL,
	"session_data" text NOT NULL,
	"expire_date" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "django_session" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "about_donatelink" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "about_donatelink_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"platform" varchar(100) NOT NULL,
	"url" varchar(200) NOT NULL,
	"order" integer NOT NULL,
	"profile_id" bigint NOT NULL,
	CONSTRAINT "about_donatelink_order_check" CHECK ("order" >= 0)
);
--> statement-breakpoint
ALTER TABLE "about_donatelink" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "core_contentversion" (
	"namespace" varchar(32) PRIMARY KEY NOT NULL,
	"version" bigint NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "core_contentversion_version_check" CHECK (version >= 0)
);
--> statement-breakpoint
ALTER TABLE "core_contentversion" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "auth_group" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auth_group_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(150) NOT NULL,
	CONSTRAINT "auth_group_name_key" UNIQUE("name")
);
--> statement-breakpoint
ALTER TABLE "auth_group" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "socialaccount_socialtoken" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "socialaccount_socialtoken_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"token" text NOT NULL,
	"token_secret" text NOT NULL,
	"expires_at" timestamp with time zone,
	"account_id" integer NOT NULL,
	"app_id" integer,
	CONSTRAINT "socialaccount_socialtoken_app_id_account_id_fca4e0ac_uniq" UNIQUE("account_id","app_id")
);
--> statement-breakpoint
ALTER TABLE "socialaccount_socialtoken" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "auth_user_groups" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auth_user_groups_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"group_id" integer NOT NULL,
	CONSTRAINT "auth_user_groups_user_id_group_id_94350c0c_uniq" UNIQUE("user_id","group_id")
);
--> statement-breakpoint
ALTER TABLE "auth_user_groups" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "openhire_portfoliohighlight" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "openhire_portfoliohighlight_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"title" varchar(255) NOT NULL,
	"description" text NOT NULL,
	"order" integer NOT NULL,
	"open_to_work_profile_id" bigint NOT NULL,
	CONSTRAINT "openhire_portfoliohighlight_order_check" CHECK ("order" >= 0)
);
--> statement-breakpoint
ALTER TABLE "openhire_portfoliohighlight" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "legal_legaldocument" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "legal_legaldocument_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"title" varchar(200) NOT NULL,
	"slug" varchar(200) NOT NULL,
	"document_type" varchar(20) NOT NULL,
	"summary" text NOT NULL,
	"is_published" boolean NOT NULL,
	"last_updated" timestamp with time zone NOT NULL,
	"sort_order" integer NOT NULL,
	CONSTRAINT "legal_legaldocument_slug_key" UNIQUE("slug"),
	CONSTRAINT "legal_legaldocument_sort_order_check" CHECK (sort_order >= 0)
);
--> statement-breakpoint
ALTER TABLE "legal_legaldocument" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "legal_legalsection" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "legal_legalsection_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"heading" varchar(200) NOT NULL,
	"body" text NOT NULL,
	"items" jsonb NOT NULL,
	"order" integer NOT NULL,
	"document_id" bigint NOT NULL,
	"parent_id" bigint,
	CONSTRAINT "legal_legalsection_order_check" CHECK ("order" >= 0)
);
--> statement-breakpoint
ALTER TABLE "legal_legalsection" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "guestbook_chatmessage" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "guestbook_chatmessage_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"message" text NOT NULL,
	"timestamp" timestamp with time zone NOT NULL,
	"reply_to_id" bigint,
	"user_id" integer NOT NULL,
	"is_pinned" boolean NOT NULL,
	"pinned_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "guestbook_chatmessage" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "about_education" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "about_education_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"degree" varchar(255) NOT NULL,
	"alias" varchar(100),
	"is_last" boolean NOT NULL,
	"achievements" jsonb NOT NULL,
	"years" varchar(50),
	"location_regency" varchar(100) NOT NULL,
	"location_province" varchar(100) NOT NULL,
	"location_prov" varchar(100) NOT NULL,
	"location_country" varchar(100) NOT NULL,
	"location_flag" varchar(16) NOT NULL,
	"location_map_url" varchar(200) NOT NULL,
	"date_start" date,
	"date_end" date,
	"organization_id" bigint NOT NULL
);
--> statement-breakpoint
ALTER TABLE "about_education" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "account_emailconfirmation" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "account_emailconfirmation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created" timestamp with time zone NOT NULL,
	"sent" timestamp with time zone,
	"key" varchar(64) NOT NULL,
	"email_address_id" integer NOT NULL,
	CONSTRAINT "account_emailconfirmation_key_key" UNIQUE("key")
);
--> statement-breakpoint
ALTER TABLE "account_emailconfirmation" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "about_organization" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "about_organization_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"logo" varchar(100),
	"website" varchar(200) NOT NULL,
	CONSTRAINT "about_organization_name_key" UNIQUE("name"),
	CONSTRAINT "about_organization_slug_key" UNIQUE("slug")
);
--> statement-breakpoint
ALTER TABLE "about_organization" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "account_emailaddress" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "account_emailaddress_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"email" varchar(254) NOT NULL,
	"verified" boolean NOT NULL,
	"primary" boolean NOT NULL,
	"user_id" integer NOT NULL,
	CONSTRAINT "account_emailaddress_user_id_email_987c8728_uniq" UNIQUE("email","user_id")
);
--> statement-breakpoint
ALTER TABLE "account_emailaddress" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "django_admin_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "django_admin_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"action_time" timestamp with time zone NOT NULL,
	"object_id" text,
	"object_repr" varchar(200) NOT NULL,
	"action_flag" smallint NOT NULL,
	"change_message" text NOT NULL,
	"content_type_id" integer,
	"user_id" integer NOT NULL,
	CONSTRAINT "django_admin_log_action_flag_check" CHECK (action_flag >= 0)
);
--> statement-breakpoint
ALTER TABLE "django_admin_log" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "django_content_type" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "django_content_type_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"app_label" varchar(100) NOT NULL,
	"model" varchar(100) NOT NULL,
	CONSTRAINT "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE("app_label","model")
);
--> statement-breakpoint
ALTER TABLE "django_content_type" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "openhire_hiringprofile" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "openhire_hiringprofile_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_name" varchar(255) NOT NULL,
	"company_description" text NOT NULL,
	"website" varchar(200) NOT NULL,
	"hiring_status" varchar(100) NOT NULL,
	"application_process" jsonb NOT NULL,
	"company_culture" jsonb NOT NULL,
	"requirements_general" jsonb NOT NULL,
	"requirements_technical" jsonb NOT NULL,
	"contact_email" varchar(254) NOT NULL,
	"contact_application_email" varchar(254) NOT NULL,
	"contact_response_time" varchar(255) NOT NULL,
	"contact_interview_process" text NOT NULL,
	"additional_notes" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "openhire_hiringprofile" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "auth_user" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auth_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"password" varchar(128) NOT NULL,
	"last_login" timestamp with time zone,
	"is_superuser" boolean NOT NULL,
	"username" varchar(150) NOT NULL,
	"first_name" varchar(150) NOT NULL,
	"last_name" varchar(150) NOT NULL,
	"email" varchar(254) NOT NULL,
	"is_staff" boolean NOT NULL,
	"is_active" boolean NOT NULL,
	"date_joined" timestamp with time zone NOT NULL,
	CONSTRAINT "auth_user_username_key" UNIQUE("username")
);
--> statement-breakpoint
ALTER TABLE "auth_user" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "auth_user_user_permissions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auth_user_user_permissions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"permission_id" integer NOT NULL,
	CONSTRAINT "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" UNIQUE("user_id","permission_id")
);
--> statement-breakpoint
ALTER TABLE "auth_user_user_permissions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "blog_blogpost" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "blog_blogpost_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"title" varchar(255) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"description" text NOT NULL,
	"author" varchar(100) NOT NULL,
	"username" varchar(100) NOT NULL,
	"author_image" varchar(100),
	"content" jsonb NOT NULL,
	"tags" jsonb NOT NULL,
	"category" varchar(100) NOT NULL,
	"is_featured" boolean NOT NULL,
	"read_time" integer,
	"views" integer NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "blog_blogpost_slug_key" UNIQUE("slug"),
	CONSTRAINT "blog_blogpost_views_check" CHECK (views >= 0)
);
--> statement-breakpoint
ALTER TABLE "blog_blogpost" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "about_experience" ADD CONSTRAINT "about_experience_organization_id_eebde7d9_fk_about_org" FOREIGN KEY ("organization_id") REFERENCES "public"."about_organization"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "blog_blogimage" ADD CONSTRAINT "blog_blogimage_blog_id_17a42bec_fk_blog_blogpost_id" FOREIGN KEY ("blog_id") REFERENCES "public"."blog_blogpost"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "about_profileskillhighlight" ADD CONSTRAINT "about_profileskillhi_profile_id_33f83da8_fk_about_pro" FOREIGN KEY ("profile_id") REFERENCES "public"."about_profile"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "about_profileskillhighlight" ADD CONSTRAINT "about_profileskillhighlight_skill_id_c59b70a2_fk_about_skill_id" FOREIGN KEY ("skill_id") REFERENCES "public"."about_skill"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "about_certification" ADD CONSTRAINT "about_certification_organization_id_be11db2d_fk_about_org" FOREIGN KEY ("organization_id") REFERENCES "public"."about_organization"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "projects_project_tech_stack" ADD CONSTRAINT "projects_project_tec_project_id_57f369fa_fk_projects_" FOREIGN KEY ("project_id") REFERENCES "public"."projects_project"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "projects_project_tech_stack" ADD CONSTRAINT "projects_project_tech_stack_skill_id_a059433c_fk_about_skill_id" FOREIGN KEY ("skill_id") REFERENCES "public"."about_skill"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "about_award" ADD CONSTRAINT "about_award_organization_id_7ae2b5b6_fk_about_organization_id" FOREIGN KEY ("organization_id") REFERENCES "public"."about_organization"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "public"."django_content_type"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "projects_projectimage" ADD CONSTRAINT "projects_projectimag_project_id_618ded0e_fk_projects_" FOREIGN KEY ("project_id") REFERENCES "public"."projects_project"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "about_journeystep" ADD CONSTRAINT "about_journeystep_application_id_a2cb78d9_fk_about_app" FOREIGN KEY ("application_id") REFERENCES "public"."about_application"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "openhire_position" ADD CONSTRAINT "openhire_position_hiring_profile_id_0b8b2dc4_fk_openhire_" FOREIGN KEY ("hiring_profile_id") REFERENCES "public"."openhire_hiringprofile"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "guestbook_userprofile" ADD CONSTRAINT "guestbook_userprofile_user_id_f1e46e02_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "public"."auth_permission"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "public"."auth_group"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "projects_feature" ADD CONSTRAINT "projects_feature_project_id_4b1ac255_fk_projects_project_id" FOREIGN KEY ("project_id") REFERENCES "public"."projects_project"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "socialaccount_socialaccount" ADD CONSTRAINT "socialaccount_socialaccount_user_id_8146e70c_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "comments_comment" ADD CONSTRAINT "comments_comment_content_type_id_72fd5dbe_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "public"."django_content_type"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "comments_comment" ADD CONSTRAINT "comments_comment_reply_to_id_c5c704af_fk_comments_comment_id" FOREIGN KEY ("reply_to_id") REFERENCES "public"."comments_comment"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "comments_comment" ADD CONSTRAINT "comments_comment_user_id_a1db4881_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "about_donatelink" ADD CONSTRAINT "about_donatelink_profile_id_5bbaaa5e_fk_about_profile_id" FOREIGN KEY ("profile_id") REFERENCES "public"."about_profile"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "socialaccount_socialtoken" ADD CONSTRAINT "socialaccount_social_account_id_951f210e_fk_socialacc" FOREIGN KEY ("account_id") REFERENCES "public"."socialaccount_socialaccount"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "socialaccount_socialtoken" ADD CONSTRAINT "socialaccount_social_app_id_636a42d7_fk_socialacc" FOREIGN KEY ("app_id") REFERENCES "public"."socialaccount_socialapp"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_user_groups" ADD CONSTRAINT "auth_user_groups_group_id_97559544_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "public"."auth_group"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_user_groups" ADD CONSTRAINT "auth_user_groups_user_id_6a12ed8b_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "openhire_portfoliohighlight" ADD CONSTRAINT "openhire_portfoliohi_open_to_work_profile_a93b04b7_fk_openhire_" FOREIGN KEY ("open_to_work_profile_id") REFERENCES "public"."openhire_opentoworkprofile"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "legal_legalsection" ADD CONSTRAINT "legal_legalsection_document_id_c0cf7e53_fk_legal_leg" FOREIGN KEY ("document_id") REFERENCES "public"."legal_legaldocument"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "legal_legalsection" ADD CONSTRAINT "legal_legalsection_parent_id_36558e12_fk_legal_legalsection_id" FOREIGN KEY ("parent_id") REFERENCES "public"."legal_legalsection"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "guestbook_chatmessage" ADD CONSTRAINT "guestbook_chatmessag_reply_to_id_995fd71d_fk_guestbook" FOREIGN KEY ("reply_to_id") REFERENCES "public"."guestbook_chatmessage"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "guestbook_chatmessage" ADD CONSTRAINT "guestbook_chatmessage_user_id_fc941c69_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "about_education" ADD CONSTRAINT "about_education_organization_id_e27bc783_fk_about_org" FOREIGN KEY ("organization_id") REFERENCES "public"."about_organization"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "account_emailconfirmation" ADD CONSTRAINT "account_emailconfirm_email_address_id_5b7f8c58_fk_account_e" FOREIGN KEY ("email_address_id") REFERENCES "public"."account_emailaddress"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "account_emailaddress" ADD CONSTRAINT "account_emailaddress_user_id_2c513194_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "public"."django_content_type"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_user_user_permissions" ADD CONSTRAINT "auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "public"."auth_permission"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_user_user_permissions" ADD CONSTRAINT "auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "about_skill_slug_2bd8fd89_like" ON "about_skill" USING btree ("slug" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "about_experience_organization_id_eebde7d9" ON "about_experience" USING btree ("organization_id" int8_ops);--> statement-breakpoint
CREATE INDEX "blog_blogimage_blog_id_17a42bec" ON "blog_blogimage" USING btree ("blog_id" int8_ops);--> statement-breakpoint
CREATE INDEX "projects_pr_is_feat_bfabaf_idx" ON "projects_project" USING btree ("is_featured" bool_ops);--> statement-breakpoint
CREATE INDEX "projects_pr_status_f023cb_idx" ON "projects_project" USING btree ("status" text_ops);--> statement-breakpoint
CREATE INDEX "projects_project_slug_2d50067a_like" ON "projects_project" USING btree ("slug" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "about_profileskillhighlight_profile_id_33f83da8" ON "about_profileskillhighlight" USING btree ("profile_id" int8_ops);--> statement-breakpoint
CREATE INDEX "about_profileskillhighlight_skill_id_c59b70a2" ON "about_profileskillhighlight" USING btree ("skill_id" int8_ops);--> statement-breakpoint
CREATE INDEX "about_certification_organization_id_be11db2d" ON "about_certification" USING btree ("organization_id" int8_ops);--> statement-breakpoint
CREATE INDEX "projects_project_tech_stack_project_id_57f369fa" ON "projects_project_tech_stack" USING btree ("project_id" int8_ops);--> statement-breakpoint
CREATE INDEX "projects_project_tech_stack_skill_id_a059433c" ON "projects_project_tech_stack" USING btree ("skill_id" int8_ops);--> statement-breakpoint
CREATE INDEX "about_award_organization_id_7ae2b5b6" ON "about_award" USING btree ("organization_id" int8_ops);--> statement-breakpoint
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" USING btree ("content_type_id" int4_ops);--> statement-breakpoint
CREATE INDEX "projects_projectimage_project_id_618ded0e" ON "projects_projectimage" USING btree ("project_id" int8_ops);--> statement-breakpoint
CREATE INDEX "about_journeystep_application_id_a2cb78d9" ON "about_journeystep" USING btree ("application_id" int8_ops);--> statement-breakpoint
CREATE INDEX "openhire_position_hiring_profile_id_0b8b2dc4" ON "openhire_position" USING btree ("hiring_profile_id" int8_ops);--> statement-breakpoint
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" USING btree ("group_id" int4_ops);--> statement-breakpoint
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" USING btree ("permission_id" int4_ops);--> statement-breakpoint
CREATE INDEX "projects_feature_project_id_4b1ac255" ON "projects_feature" USING btree ("project_id" int8_ops);--> statement-breakpoint
CREATE INDEX "socialaccount_socialaccount_user_id_8146e70c" ON "socialaccount_socialaccount" USING btree ("user_id" int4_ops);--> statement-breakpoint
CREATE INDEX "comments_co_content_7dda54_idx" ON "comments_comment" USING btree ("content_type_id" int4_ops,"object_id" timestamptz_ops,"created_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "comments_comment_content_type_id_72fd5dbe" ON "comments_comment" USING btree ("content_type_id" int4_ops);--> statement-breakpoint
CREATE INDEX "comments_comment_created_at_c684ddb5" ON "comments_comment" USING btree ("created_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "comments_comment_reply_to_id_c5c704af" ON "comments_comment" USING btree ("reply_to_id" int8_ops);--> statement-breakpoint
CREATE INDEX "comments_comment_user_id_a1db4881" ON "comments_comment" USING btree ("user_id" int4_ops);--> statement-breakpoint
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" USING btree ("expire_date" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "django_session_session_key_c0390e0f_like" ON "django_session" USING btree ("session_key" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "about_donatelink_profile_id_5bbaaa5e" ON "about_donatelink" USING btree ("profile_id" int8_ops);--> statement-breakpoint
CREATE INDEX "core_contentversion_namespace_bb92bc58_like" ON "core_contentversion" USING btree ("namespace" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "auth_group_name_a6ea08ec_like" ON "auth_group" USING btree ("name" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "socialaccount_socialtoken_account_id_951f210e" ON "socialaccount_socialtoken" USING btree ("account_id" int4_ops);--> statement-breakpoint
CREATE INDEX "socialaccount_socialtoken_app_id_636a42d7" ON "socialaccount_socialtoken" USING btree ("app_id" int4_ops);--> statement-breakpoint
CREATE INDEX "auth_user_groups_group_id_97559544" ON "auth_user_groups" USING btree ("group_id" int4_ops);--> statement-breakpoint
CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "auth_user_groups" USING btree ("user_id" int4_ops);--> statement-breakpoint
CREATE INDEX "openhire_portfoliohighlight_open_to_work_profile_id_a93b04b7" ON "openhire_portfoliohighlight" USING btree ("open_to_work_profile_id" int8_ops);--> statement-breakpoint
CREATE INDEX "legal_legal_is_publ_03b95d_idx" ON "legal_legaldocument" USING btree ("is_published" text_ops,"slug" bool_ops);--> statement-breakpoint
CREATE INDEX "legal_legaldocument_slug_d0cf8ba1_like" ON "legal_legaldocument" USING btree ("slug" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "legal_legal_documen_83d36e_idx" ON "legal_legalsection" USING btree ("document_id" int4_ops,"order" int8_ops);--> statement-breakpoint
CREATE INDEX "legal_legalsection_document_id_c0cf7e53" ON "legal_legalsection" USING btree ("document_id" int8_ops);--> statement-breakpoint
CREATE INDEX "legal_legalsection_parent_id_36558e12" ON "legal_legalsection" USING btree ("parent_id" int8_ops);--> statement-breakpoint
CREATE INDEX "guestbook_c_timesta_c27cf0_idx" ON "guestbook_chatmessage" USING btree ("timestamp" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "guestbook_c_user_id_2b80f5_idx" ON "guestbook_chatmessage" USING btree ("user_id" int4_ops,"timestamp" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "guestbook_chatmessage_reply_to_id_995fd71d" ON "guestbook_chatmessage" USING btree ("reply_to_id" int8_ops);--> statement-breakpoint
CREATE INDEX "guestbook_chatmessage_timestamp_5ed2bcc7" ON "guestbook_chatmessage" USING btree ("timestamp" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "guestbook_chatmessage_user_id_fc941c69" ON "guestbook_chatmessage" USING btree ("user_id" int4_ops);--> statement-breakpoint
CREATE INDEX "guestbook_pinned_idx" ON "guestbook_chatmessage" USING btree ("is_pinned" timestamptz_ops,"pinned_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "about_education_organization_id_e27bc783" ON "about_education" USING btree ("organization_id" int8_ops);--> statement-breakpoint
CREATE INDEX "account_emailconfirmation_email_address_id_5b7f8c58" ON "account_emailconfirmation" USING btree ("email_address_id" int4_ops);--> statement-breakpoint
CREATE INDEX "account_emailconfirmation_key_f43612bd_like" ON "account_emailconfirmation" USING btree ("key" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "about_organization_name_0a2284da_like" ON "about_organization" USING btree ("name" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "about_organization_slug_6a861254_like" ON "about_organization" USING btree ("slug" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "account_emailaddress_email_03be32b2" ON "account_emailaddress" USING btree ("email" text_ops);--> statement-breakpoint
CREATE INDEX "account_emailaddress_email_03be32b2_like" ON "account_emailaddress" USING btree ("email" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "account_emailaddress_user_id_2c513194" ON "account_emailaddress" USING btree ("user_id" int4_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "unique_primary_email" ON "account_emailaddress" USING btree ("user_id" int4_ops,"primary" bool_ops) WHERE "primary";--> statement-breakpoint
CREATE UNIQUE INDEX "unique_verified_email" ON "account_emailaddress" USING btree ("email" text_ops) WHERE verified;--> statement-breakpoint
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" USING btree ("content_type_id" int4_ops);--> statement-breakpoint
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" USING btree ("user_id" int4_ops);--> statement-breakpoint
CREATE INDEX "auth_user_username_6821ab7c_like" ON "auth_user" USING btree ("username" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "auth_user_user_permissions" USING btree ("permission_id" int4_ops);--> statement-breakpoint
CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "auth_user_user_permissions" USING btree ("user_id" int4_ops);--> statement-breakpoint
CREATE INDEX "blog_blogpo_is_feat_aa3e07_idx" ON "blog_blogpost" USING btree ("is_featured" bool_ops);--> statement-breakpoint
CREATE INDEX "blog_blogpost_slug_9e84ade1_like" ON "blog_blogpost" USING btree ("slug" varchar_pattern_ops);
*/