# Generated by Django 6.0.6 on 2026-08-09 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('In Progress', 'In Progress'), ('Withdrawn', 'Withdrawn'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Ghosted', 'Ghosted')], max_length=20)),
                ('company_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('employment_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Self-employed', 'Self-employed'), ('Freelance', 'Freelance'), ('Contract', 'Contract'), ('Internship', 'Internship'), ('Apprenticeship', 'Apprenticeship'), ('Seasonal', 'Seasonal'), ('Scholarship', 'Scholarship')], max_length=20)),
                ('location_type', models.CharField(choices=[('On-site', 'On-site'), ('Hybrid', 'Hybrid'), ('Remote', 'Remote')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('applied_via', models.CharField(blank=True, choices=[('LinkedIn', 'LinkedIn'), ('GitHub', 'GitHub'), ('MagangHub', 'MagangHub'), ('Talenta IT', 'Talenta IT'), ('Dealls', 'Dealls'), ('Katrecs', 'Katrecs'), ('Humanis.id', 'Humanis.id'), ('Other', 'Other')], max_length=20, null=True)),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('lessons_learned', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('credential_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('institution', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('issued_month', models.CharField(max_length=10)),
                ('issued_year', models.IntegerField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('credential_url', models.URLField(blank=True)),
                ('institution', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('is_featured', models.BooleanField(default=False)),
                ('achievements', models.JSONField(blank=True, default=list)),
                ('issued_month', models.CharField(max_length=10)),
                ('issued_year', models.IntegerField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('is_last', models.BooleanField(default=False)),
                ('achievements', models.JSONField(blank=True, default=list)),
                ('years', models.CharField(blank=True, max_length=50, null=True)),
                ('date_start_month', models.CharField(blank=True, max_length=10, null=True)),
                ('date_start_year', models.IntegerField(blank=True, null=True)),
                ('date_end_month', models.CharField(blank=True, max_length=10, null=True)),
                ('date_end_year', models.IntegerField(blank=True, null=True)),
                ('location_regency', models.CharField(blank=True, max_length=100)),
                ('location_province', models.CharField(blank=True, max_length=100)),
                ('location_prov', models.CharField(blank=True, max_length=100)),
                ('location_country', models.CharField(blank=True, max_length=100)),
                ('location_flag', models.CharField(blank=True, max_length=16)),
                ('location_map_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('website', models.URLField(blank=True)),
                ('period_start_month', models.CharField(max_length=10)),
                ('period_start_year', models.IntegerField()),
                ('period_end_month', models.CharField(blank=True, max_length=10, null=True)),
                ('period_end_year', models.IntegerField(blank=True, null=True)),
                ('employment_type', models.CharField(max_length=50)),
                ('location_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('is_current', models.BooleanField(default=False)),
                ('responsibilities', models.JSONField(blank=True, default=list)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('aka', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('personal_website', models.URLField(blank=True)),
                ('cv_main', models.URLField(blank=True)),
                ('cv_latest', models.URLField(blank=True)),
                ('cv_copy', models.URLField(blank=True)),
                ('role', models.CharField(max_length=255)),
                ('is_open_to_work', models.BooleanField(default=False)),
                ('is_hiring', models.BooleanField(default=False)),
                ('is_sick', models.BooleanField(default=False)),
                ('short_description', models.TextField(blank=True)),
                ('short_bio', models.TextField(blank=True)),
                ('short_cta', models.TextField(blank=True)),
                ('long_description', models.TextField(blank=True)),
                ('stories', models.JSONField(blank=True, default=list)),
                ('skills_highlight', models.JSONField(blank=True, default=list)),
                ('location_regency', models.CharField(blank=True, max_length=100)),
                ('location_residency', models.CharField(blank=True, max_length=100)),
                ('location_province', models.CharField(blank=True, max_length=100)),
                ('location_prov', models.CharField(blank=True, max_length=100)),
                ('location_country', models.CharField(blank=True, max_length=100)),
                ('location_flag', models.CharField(blank=True, max_length=16)),
                ('social_email', models.EmailField(blank=True, max_length=254)),
                ('social_github', models.URLField(blank=True)),
                ('social_linkedin', models.URLField(blank=True)),
                ('social_follow_linkedin', models.URLField(blank=True)),
                ('social_instagram', models.URLField(blank=True)),
                ('social_medium', models.URLField(blank=True)),
                ('social_x', models.URLField(blank=True)),
                ('social_website', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon_svg', models.CharField(blank=True, max_length=500)),
                ('category', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='JourneyStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_steps', to='about.application')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DonateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donate_links', to='about.profile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
