# Generated by Django 6.0.7 on 2026-08-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='employment_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Self-employed', 'Self-employed'), ('Freelance', 'Freelance'), ('Contract', 'Contract'), ('Internship', 'Internship'), ('Apprenticeship', 'Apprenticeship'), ('Seasonal', 'Seasonal'), ('Scholarship', 'Scholarship')], max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='location_type',
            field=models.CharField(choices=[('On-site', 'On-site'), ('Hybrid', 'Hybrid'), ('Remote', 'Remote')], max_length=50),
        ),
    ]
