# Generated by Django 6.0.6 on 2026-08-09 01:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('overview', models.TextField(blank=True)),
                ('policy_updates', models.TextField(blank=True)),
                ('data_collected', models.JSONField(blank=True, default=dict)),
                ('data_usage', models.JSONField(blank=True, default=dict)),
                ('third_party_services', models.JSONField(blank=True, default=dict)),
                ('data_protection', models.JSONField(blank=True, default=dict)),
                ('user_rights', models.JSONField(blank=True, default=dict)),
                ('guestbook_limitations', models.JSONField(blank=True, default=dict)),
                ('email_communications', models.JSONField(blank=True, default=dict)),
                ('legal_basis', models.JSONField(blank=True, default=dict)),
                ('cookies', models.JSONField(blank=True, default=dict)),
                ('copyright_credits', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Privacy Policy',
                'verbose_name_plural': 'Privacy Policy',
            },
        ),
    ]
