# Generated by Django 6.0.6 on 2026-08-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentVersion',
            fields=[
                ('namespace', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Content Version',
                'verbose_name_plural': 'Content Versions',
            },
        ),
    ]
