# Generated by Django 6.0.7 on 2026-08-16 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0002_migrate_privacy_policy"),
        ('core', '0002_contentversion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivacyPolicy',
        ),
    ]
