# Generated by Django 5.2.5 on 2025-06-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='co_author_order',
            field=models.PositiveIntegerField(default=0, help_text='Order of co-author assignment (for FIFO removal)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_co_author',
            field=models.BooleanField(default=False, help_text='Designates whether this user is a co-author (max 2)'),
        ),
    ]
