# Generated by Django 5.2.5 on 2025-09-01 10:42

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0002_userprofile_co_author_order_userprofile_is_co_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['-timestamp'], name='guestbook_c_timesta_c27cf0_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['user', '-timestamp'], name='guestbook_c_user_id_2b80f5_idx'),
        ),
    ]
