"""
Configuration loader for FlexForge project.
Centralizes environment variables and external keys.

Author: Ridwan Halim (ridwaanhall.com)
License: Apache License 2.0
Created at: March 16, 2025
"""

from email.utils import formataddr, parseaddr
from pathlib import Path

from decouple import Csv, config


def _load_env_local() -> None:
    """Merge .env.local (gitignored, generated by `vercel env pull` from the
    Supabase integration) into the process environment so decouple's config()
    picks it up locally. In production, Vercel injects these same STORAGE_*
    vars directly into the environment and no .env.local file is deployed, so
    this is a local-dev-only convenience, not a second source of truth."""
    import os

    env_local_path = Path(__file__).resolve().parent.parent / ".env.local"
    if not env_local_path.exists():
        return
    for line in env_local_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


_load_env_local()

# --------------------------------------------------------------------------
# ENVIRONMENT FLAGS
# --------------------------------------------------------------------------
DEBUG = config("DEBUG", default=False, cast=bool)

# --------------------------------------------------------------------------
# SECURITY KEYS
# --------------------------------------------------------------------------
SECRET_KEY = config("SECRET_KEY")
ACCESS_TOKEN = config("ACCESS_TOKEN")
WAKATIME_API_KEY = config("WAKATIME_API_KEY", default="")

# --------------------------------------------------------------------------
# CLOUDFLARE TURNSTILE
# --------------------------------------------------------------------------
USE_CF_TURNSTILE = config("USE_CF_TURNSTILE", default=True, cast=bool)
CF_TURNSTILE_SITE_KEY = config("CF_TURNSTILE_SITE_KEY", default="")
CF_TURNSTILE_SECRET_KEY = config("CF_TURNSTILE_SECRET_KEY", default="")

# --------------------------------------------------------------------------
# BASE URLS
# --------------------------------------------------------------------------
BASE_URL = config("BASE_URL", default="http://127.0.0.1:8000" if DEBUG else "https://ridwaanhall.com")

# --------------------------------------------------------------------------
# HOSTS
# --------------------------------------------------------------------------
ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="", cast=Csv()) if DEBUG else [
    ".vercel.app",
    ".ridwaanhall.com",
]

# --------------------------------------------------------------------------
# EMAIL
# --------------------------------------------------------------------------
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
_raw_default_from_email = config("DEFAULT_FROM_EMAIL", default=EMAIL_HOST_USER)
_from_name, _from_addr = parseaddr(_raw_default_from_email)
if not _from_addr:
    _from_addr = _raw_default_from_email
DEFAULT_FROM_EMAIL = formataddr((_from_name or "ridwaanhall.com", _from_addr))
CONTACT_EMAIL_RECIPIENT = config("CONTACT_EMAIL_RECIPIENT", default="hi@ridwaanhall.com", cast=Csv())

# --------------------------------------------------------------------------
# FEATURE FLAGS
# --------------------------------------------------------------------------
GUESTBOOK_PAGE = config("GUESTBOOK_PAGE", default=True, cast=bool)
WSRV_IMAGE_OPTIMIZATION = config("WSRV_IMAGE_OPTIMIZATION", default=not DEBUG, cast=bool)

# --------------------------------------------------------------------------
# PAGINATIONS
# --------------------------------------------------------------------------
ITEMS_PER_PAGE = 10

# --------------------------------------------------------------------------
# SOCIAL AUTH KEYS (Guestbook only)
# --------------------------------------------------------------------------
GOOGLE_CLIENT_ID = config("GOOGLE_CLIENT_ID", default="")
GOOGLE_CLIENT_SECRET = config("GOOGLE_CLIENT_SECRET", default="")
GH_CLIENT_ID = config("GH_CLIENT_ID", default="")
GH_CLIENT_SECRET = config("GH_CLIENT_SECRET", default="")

# --------------------------------------------------------------------------
# DATABASE (Supabase Postgres in production)
# --------------------------------------------------------------------------
# Pooled (pgbouncer, transaction mode) connection -- used for runtime app traffic
# under Vercel's serverless model, where many short-lived connections would
# otherwise exhaust Postgres's max_connections.
DATABASE_URL = config("STORAGE_POSTGRES_URL", default="")
# Direct (non-pooled) connection -- used for migrate/admin commands, since DDL
# is unreliable behind a transaction-mode pooler.
DATABASE_URL_DIRECT = config("STORAGE_POSTGRES_URL_NON_POOLING", default="")

# --------------------------------------------------------------------------
# SUPABASE STORAGE (media: blog/project images, logos, profile photo)
# --------------------------------------------------------------------------
SUPABASE_URL = config("STORAGE_SUPABASE_URL", default="")
SUPABASE_SERVICE_ROLE_KEY = config("STORAGE_SUPABASE_SERVICE_ROLE_KEY", default="")
SUPABASE_STORAGE_BUCKET = config("SUPABASE_STORAGE_BUCKET", default="media")